[package]
name = "crowbook-server"
version = "0.10.0"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]

[dependencies]
iron = "0.4"
crowbook = "0.10"
router = "0.4"
urlencoded = "0.4"
hyper = "0.9"
tempfile = "2"
